version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bdusername
      - MARIADB_PASSWORD=bdpassword
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  opencart:
    image: 'opencart-phpmyadmin-img'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - OPENCART_HOST=misitio.com
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bdusername
      - OPENCART_DATABASE_PASSWORD=bdpassword
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_USERNAME=admin
      - OPENCART_PASSWORD=password
      - OPENCART_EMAIL="emailg@misitio.com"
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
